//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outpatientsystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugView
    {
        public string 编号 { get; set; }
        public string 药名 { get; set; }
        public string 拼音 { get; set; }
        public double 数量 { get; set; }
        public string 单位 { get; set; }
        public string 分类编号 { get; set; }
        public string 药品分类 { get; set; }
    }
}
