//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outpatientsystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Diagnosticlist
    {
        public string No { get; set; }
        public string BookingNo { get; set; }
        public System.DateTime Time { get; set; }
        public string Content { get; set; }
        public string ZZ { get; set; }
        public string PriceType { get; set; }
        public Nullable<double> Prices { get; set; }
        public Nullable<bool> Paid { get; set; }
    
        public virtual tb_Booking tb_Booking { get; set; }
    }
}
