//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outpatientsystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Drug
    {
        public string No { get; set; }
        public string Name { get; set; }
        public string pinyin { get; set; }
        public double Num { get; set; }
        public string UNIT { get; set; }
        public string PharmacyNo { get; set; }
        public string TypeNo { get; set; }
        public string Content { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual tb_Pharmacy tb_Pharmacy { get; set; }
        public virtual tb_Type tb_Type { get; set; }
    }
}
