//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outpatientsystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Doctor()
        {
            this.tb_Worksheet = new HashSet<tb_Worksheet>();
        }
    
        public string No { get; set; }
        public byte[] Password { get; set; }
        public string Pinyin { get; set; }
        public string Name { get; set; }
        public bool Gender { get; set; }
        public string Introduction { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string KeshiNo { get; set; }
        public string ProtitleNo { get; set; }
        public Nullable<int> FailCount { get; set; }
    
        public virtual tb_Keshi tb_Keshi { get; set; }
        public virtual tb_Pro_title tb_Pro_title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_Worksheet> tb_Worksheet { get; set; }
    }
}
