//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outpatientsystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class WYView
    {
        public string 预约号 { get; set; }
        public string 患者编号 { get; set; }
        public string 患者姓名 { get; set; }
        public System.DateTime 预约时间 { get; set; }
        public string 医生名字 { get; set; }
        public string 医生编号 { get; set; }
        public string 是否就诊 { get; set; }
        public string 处理 { get; set; }
    }
}
