//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Outpatientsystem.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZDView
    {
        public string NO { get; set; }
        public string Pno { get; set; }
        public string Pname { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public string ZZ { get; set; }
        public string DoctorName { get; set; }
        public string KeSi { get; set; }
        public string PriceType { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Price { get; set; }
    }
}
